services:
  nginx:
    depends_on:
      - php
    build:
      context: .
      dockerfile: ./nginx/dockerfile
    container_name: nginx
    volumes:
      - ./php/framework:/var/www/html
    ports:
      - '8080:80'
  php:
    depends_on:
      - mysql
    build: 
      context: .
      dockerfile: ./php/dockerfile
    container_name: frameworkx
    volumes:
      - ./php/framework:/var/www/html
  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - '13306:3306'
    environment:
      MYSQL_DATABASE: framework
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: framework
      MYSQL_PASSWORD: framework
volumes:
  mysql:
    driver: local