FROM php:8.2-fpm

COPY ./php/config/php.ini /usr/local/etc/php/
COPY ./php/config/composer.sh /usr/local/bin/composer-installer

RUN apt-get -yqq update \
    && apt-get -yqq install --no-install-recommends zip unzip libpng-dev libjpeg-dev libfreetype6-dev zlib1g-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install mysqli pdo pdo_mysql gd \
    && docker-php-ext-enable pdo_mysql gd \
    && chmod +x  /usr/local/bin/composer-installer \
    && composer-installer \
    && mv composer.phar /usr/local/bin/composer \
    && chmod +x /usr/local/bin/composer \
    && composer --version
    
WORKDIR /tmp
COPY ./php/invoice-generator/composer.json /tmp
RUN composer install \
    --no-interaction \
    --no-plugins \
    --no-scripts \
    --prefer-dist \
    && rm -rf composer.json composer.lock vendor/

WORKDIR /var/www/html
COPY ./php/invoice-generator /var/www/html
RUN composer install \
    --no-interaction \
    --no-plugins \
    --no-scripts \
    --prefer-dist
